@host = http://localhost:3000
@baseUrl = {{host}}/api/v1
@contenType = application/json

POST {{baseUrl}}/books
Content-Type: {{contenType}}

  {
    "title": "O Senhor dos Anéis",
    "subtitle": "O Retorno do Rei",
    "author": "J.R.R. Tolkien",
    "genre": "Fantasia",
    "cover": "https://harpercollins.com.br/cdn/shop/products/9786555113662_44bc4e0d-f1c5-4ae0-9df5-ae703095b13d.jpg"
  }

###
GET {{baseUrl}}/books
Content-Type: {{contenType}}

###
GET {{baseUrl}}/books/66b3db764301f614d730ab64
Content-Type: {{contenType}}

###
PUT {{baseUrl}}/books/66b3db764301f614d730ab64
Content-Type: {{contenType}}

{
  "subtitle": "As Duas Torres",
  "cover": "https://harpercollins.com.br/cdn/shop/products/9786555113624_84e92bc9-fe5b-4d2c-9c79-5d2153540499.jpg"
}

###
DELETE {{baseUrl}}/books/66b3dd144301f614d730ab6f
Content-Type: {{contenType}}
